### PR TITLE
Add option to extend existing metadata.json

### PR DESCRIPTION
**Pull request by wojtek-oledzki**
In case when you don't keep all your box files locally, and you want to
only add new version you can now use `--append` option.

### CODE REVIEW

**Comment by wojtek-oledzki** [comment]
@lvillani any thoughts on this PR?

**Comment by lvillani** [comment]
Hey @wojtek-oledzki, sorry for being unresponsive. Looks good! Thanks 👍

**Comment by lvillani** [comment]
I pushed version 1.1.0 to PyPI which should include this change.

**Comment by wojtek-oledzki** [comment]
much appreciated @lvillani !!

**Pull request merged**
